# -*- coding: UTF-8 -*-

#  Aeryn2 -- a unit test framework for C++.
#
#  Copyright © 2005 Russel Winder
#  
#  This library is free software; you can redistribute it and/or modify it under the terms of
#  the GNU Lesser General Public License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#  
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU Lesser General Public License for more details.
# 
#  You should have received a copy of the GNU Lesser General Public License along with this
#  library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA 02111-1307, USA

import os.path

Import ( 'env' )

e = env.Copy ( )
e.Replace ( LIBPATH = env [ 'LIB_DIR' ] )
e.Replace ( LIBS = [ 'aeryn_tests' , 'aeryn_core' ] )

components = [
           'main.cpp' ,
           'simple_calc.cpp' ,
           'simple_calc_test.cpp'
]

executable = os.path.join ( e [ 'BIN_DIR' ] , 'TestClient2' )

main = e.Program ( 'main' , components  )
e.InstallAs ( executable , main )

Command ( 'test.execute' , executable , 'LD_LIBRARY_PATH=' + e [ 'LIB_DIR' ] [ 1: ] + ' $SOURCES' )
