# -*- coding: UTF-8 -*-

#  Aeryn2 -- a unit test framework for C++.
#
#  Copyright © 2005 Russel Winder
#  
#  This library is free software; you can redistribute it and/or modify it under the terms of
#  the GNU Lesser General Public License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#  
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU Lesser General Public License for more details.
# 
#  You should have received a copy of the GNU Lesser General Public License along with this
#  library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA 02111-1307, USA

#  SConscript file for building the Aeryn tests.

import os
import re

libraryName = 'aeryn_tests'
librarySource = [ file for file in os.listdir ( '.' ) if re.compile ( ".*\.cpp" ).search ( file ) ]

Import ( 'env' )

e = env.Copy ( )

libDir = e [ 'LIB_DIR' ]

versionNumber = e [ 'VERSION_NUMBER' ]
baseName = e.subst( '$SHLIBPREFIX' ) + libraryName + e [ 'SHLIBSUFFIX' ]
basePath = os.path.join ( libDir , baseName )
fullName = baseName + '.' + versionNumber
fullPath = os.path.join ( libDir , fullName )
soName = baseName + '.' + versionNumber.split ( '.' )[0]
soPath = os.path.join ( libDir , soName )

staticLibrary = e.StaticLibrary ( libraryName , librarySource )
e.Install ( e [ 'LIB_DIR' ] , staticLibrary )

#  Building shared libraries on Windows is more trouble than it is worth.

if e [ 'PLATFORM' ] != 'win32' and e [ 'PLATFORM' ] != 'cygwin' :
  e.Append ( SHLINKFLAGS = '-Wl,-soname,' +  soName )
  sharedLibrary = e.SharedLibrary ( libraryName , librarySource )
  if str ( sharedLibrary[0] ) != baseName :
    print "******************************************** PANIC NOW *****************************"
    print 'produced = ' + str ( sharedLibrary[0] )
    print 'expected = ' + baseName
  e.InstallAs ( fullPath , sharedLibrary )
  libDir = libDir[1:]
  e.Command ( basePath , fullPath , 'cd ' + libDir + ' && ln -s ' + fullName + ' ' + baseName )
  e.Command ( soPath , fullPath , 'cd ' + libDir + ' && ln -s ' + fullName + ' ' + soName )
